CREATE TABLE IF NOT EXISTS IF NOT EXISTS mtl_city_code(
"_id" TEXT, "Nom Officiel" TEXT, "Nom aberge" TEXT, Acronyme TEXT, "Code 3L" TEXT, "ID-uadm" TEXT, "No-arro-election" TEXT, "Code REM" TEXT
);

CREATE TABLE IF NOT EXISTS IF NOT EXISTS mtl_crimes (_id TEXT,CATEGORIE TEXT ,"DATE" TEXT ,QUART TEXT,PDQ TEXT,X TEXT,Y TEXT,LONGITUDE TEXT,LATITUDE TEXT);

CREATE TABLE IF NOT EXISTS IF NOT EXISTS mtl_Bugs(
"_id" TEXT,NO_DECLARATION TEXT,DATE_DECLARATION TEXT,DATE_INSP_VISPRE TEXT,NBR_EXTERMIN TEXT,DATE_DEBUTTRAIT TEXT,DATE_FINTRAIT TEXT,No_QR TEXT,NOM_QR TEXT,NOM_ARROND TEXT,COORD_X TEXT,COORD_Y TEXT,LONGITUDE TEXT,LATITUDE TEXT
);

CREATE TABLE IF NOT EXISTS mtl_business(
"_id" TEXT,Numero_Fournisseur TEXT,Nom_Fournisseur TEXT,Autre_Nom TEXT,Num_Entreprise_Quebec TEXT,Structure_Juridique TEXT,Nombre_Employes TEXT,Nombre_Employes_Montreal TEXT,Politique_Dans_Dev_Durable TEXT,Politique_Approv_Responsable TEXT,Entreprise_Start_Up TEXT,Fournisseur_RTU TEXT, Entreprise_Economie_Sociale TEXT,Lieu_Arrondissement TEXT,Lieu_Ville TEXT,Lieu_Etat_Province TEXT,Lieu_Pays TEXT,Lieu_Zone_Achat TEXT
);

CREATE TABLE IF NOT EXISTS mtl_commercial_sites(
"_id" TEXT, "ID" TEXT, ORIGINE TEXT,T_COMMERCE TEXT,DATE_CREATION TEXT,CIVIQUE TEXT,TYPE_VOIE TEXT,LIEN_VOIE TEXT,NOM_VOIE TEXT,ORIENTATION TEXT,ADRESSE TEXT,SUITE TEXT,ETAGE TEXT,NOM_CENTRE TEXT,NOM_ETAB TEXT,ID_USAGE1 TEXT,USAGE1 TEXT,ID_USAGE2 TEXT,USAGE2 TEXT,ID_USAGE3 TEXT,USAGE3 TEXT,SCIAN TEXT,ACCES_MOBILITE_REDUITE TEXT,VACANT_A_LOUER TEXT,ARRONDISSEMENT TEXT, QUARTIER TEXT,SDC_NOM TEXT,SECTEUR_PME TEXT,ENFANT TEXT,MULTIUSAGE TEXT,MULTIOCCUPANT TEXT,COORDY TEXT,COORDX TEXT,LAT TEXT,LONG TEXT
);



CREATE TABLE IF NOT EXISTS to_crimes ("_id" TEXT,AREA_NAME TEXT,HOOD_ID TEXT,POPULATION_2024 TEXT,geometry TEXT,crime TEXT,"year" TEXT,"count" TEXT,rate TEXT);



CREATE TABLE IF NOT EXISTS mtl_financial_help(
"_id" TEXT,titre TEXT,url_fiche TEXT,service_publieur TEXT,date_cree TEXT,"type" TEXT,statut TEXT
);

CREATE TABLE IF NOT EXISTS mtl_fines_food(
"_id" TEXT,id_poursuite TEXT,business_id TEXT,date TEXT,description TEXT,adresse TEXT,date_jugement TEXT,etablissement TEXT,montant TEXT,proprietaire TEXT,ville TEXT,statut TEXT,date_statut TEXT,categorie TEXT
);

CREATE TABLE IF NOT EXISTS mtl_food_establishments(
"_id" TEXT,business_id TEXT,"name" TEXT,address TEXT,city TEXT,"state" TEXT,"type" TEXT,statut TEXT,date_statut TEXT,latitude TEXT,longitude TEXT,x TEXT,y TEXT
);

CREATE TABLE IF NOT EXISTS mtl_green_transportation(
"_id" TEXT,unite_administrative TEXT,automobile_electrique TEXT,automobile_hybride TEXT,camion_leger_electrique TEXT,veh_outil_leger_electrique TEXT,veh_outil_lourd_electrique TEXT,autre_equipement_leger_electrique TEXT,total_general TEXT
);

CREATE TABLE IF NOT EXISTS mtl_index_quality_life(
"_id" TEXT,adidu TEXT,arr_ville TEXT,"type" TEXT,pop2021 TEXT,log_priv2021 TEXT,mono_pr TEXT,imm_recent_pr TEXT,autoch_minor_pr TEXT,sans_diplome_pr TEXT,pr_men_bil TEXT,pr_ind_mpc TEXT,pr_log_autor_axes_ps TEXT,pr_laeq60pl TEXT,pr_nocanop TEXT,pr_indust300m TEXT,pr_logchaleur TEXT,mefaits_pond TEXT,collisions_rt TEXT,crimes_pond TEXT,nb_commerces_alimentaires_moyenne_ponderee TEXT,nb_organismes_communautaires_moyenne_ponderee TEXT,nb_pharmacies_moyenne_ponderee TEXT,nb_ecoles_primaires_moyenne_ponderee TEXT,nb_pass_tc TEXT,nb_emplois_acces_tc_30min TEXT,nb_biblio_lieux_cult_principaux_moy_pond TEXT,nb_equipement_distinct_moy_pond TEXT,superficie_parc_accessible_moy_pond TEXT,ACP_sociale TEXT,ACP_econo TEXT,ACP_environn TEXT,ACP_securite TEXT,ACP_proximite TEXT,ACP_CultSportLoisir TEXT,ACP_sociale_2quintiles TEXT,ACP_econo_2quintiles TEXT,ACP_enviro_2quintiles TEXT,ACP_securite_2quintiles TEXT,ACP_proximite_2quintiles TEXT,ACP_CultSportLoisir_2quintiles TEXT,Indice_emv TEXT
);

CREATE TABLE IF NOT EXISTS mtl_Municipalities(
"_id" TEXT,mcode TEXT,munnom TEXT,madr1 TEXT,madr2 TEXT,madr3 TEXT,madr4 TEXT,mcodpos TEXT,mcourriel TEXT,mweb TEXT,mtel TEXT,mfax TEXT,mcodedesi TEXT,mdes TEXT,mgentile TEXT,regadm TEXT,divrec TEXT,mrc TEXT,admregionale TEXT,horsmrcautoch TEXT,mdatcons TEXT,mdatregi TEXT,msuperf TEXT,mpopul TEXT,datelec TEXT,electype TEXT,delectype TEXT,elecmode TEXT,delecmode TEXT,divter TEXT,mcm TEXT,mcirc TEXT,msupft TEXT,maire TEXT,con1 TEXT,con2 TEXT,con3 TEXT,con4 TEXT,con5 TEXT,con6 TEXT,con7 TEXT,con8 TEXT,con9 TEXT,con10 TEXT,con11 TEXT,con12 TEXT,con13 TEXT,con14 TEXT,con15 TEXT,con16 TEXT,con17 TEXT,con18 TEXT,con19 TEXT,con20 TEXT,con21 TEXT,con22 TEXT,con23 TEXT,con24 TEXT,con25 TEXT,con26 TEXT,con27 TEXT,con28 TEXT,con29 TEXT,con30 TEXT,con31 TEXT,con32 TEXT,con33 TEXT,con34 TEXT,con35 TEXT,con36 TEXT,con37 TEXT,con38 TEXT,con39 TEXT,con40 TEXT,con41 TEXT,con42 TEXT,con43 TEXT,con44 TEXT,con45 TEXT,con46 TEXT,con47 TEXT,con48 TEXT,con49 TEXT,con50 TEXT,con51 TEXT,con52 TEXT,con53 TEXT,con54 TEXT,con55 TEXT,con56 TEXT,con57 TEXT,con58 TEXT,con59 TEXT,con60 TEXT,con61 TEXT,con62 TEXT,con63 TEXT,con64 TEXT,con65 TEXT,con66 TEXT,con67 TEXT,con68 TEXT,con69 TEXT,con70 TEXT,con71 TEXT,con72 TEXT,con73 TEXT,con74 TEXT,con75 TEXT,dirgen TEXT,dirsecpub TEXT,tres TEXT,gref TEXT,sectres TEXT,polic TEXT,incen TEXT,loisir TEXT,trvpub TEXT,mesurg TEXT,urban TEXT,communic TEXT,permis TEXT,batim TEXT,nd TEXT
);

CREATE TABLE IF NOT EXISTS mtl_parc(
"_id" TEXT,titre_lieu TEXT,url_fiche TEXT,description TEXT,date_cree TEXT,date_revision TEXT,arrondissements TEXT,"types" TEXT,installations TEXT,activites TEXT,commodites TEXT,accessibilite TEXT,categories TEXT,statut_ouverture TEXT,horaire_par_jour TEXT,commentaires_horaire TEXT,reglementation TEXT,paiement TEXT,telephone TEXT,courriel TEXT,titre_lieu_adresse_postale TEXT,adresse_principale TEXT,adresse_secondaire TEXT,code_postal TEXT,ville TEXT,lat TEXT,long TEXT,X TEXT,Y TEXT
);

CREATE TABLE IF NOT EXISTS mtl_parking_fines(
 "_id" TEXT,NO_SECTEUR_SSE TEXT,NOM_SECTEUR_SSE TEXT,ARR_SECTEUR TEXT,NO_PERMIS TEXT,DATE_ACTION_SHP TEXT,TOTAL_RECU TEXT
);

CREATE TABLE IF NOT EXISTS mtl_Passenger_count(
 "_id" TEXT,Id_Reference TEXT,Id_Intersection TEXT,Nom_Intersection TEXT,"Date" TEXT,Periode TEXT,Heure TEXT,"Minute" TEXT,Seconde TEXT,Code_Banque TEXT,Description_Code_Banque TEXT,NBLT TEXT,NBT TEXT,NBRT TEXT,SBLT TEXT,SBT TEXT,SBRT TEXT,EBLT TEXT,EBT TEXT,EBRT TEXT,WBLT TEXT,WBT TEXT,WBRT TEXT,Approche_Nord TEXT,Approche_Sud TEXT,Approche_Est TEXT,Approche_Ouest TEXT,Localisation_X TEXT,Localisation_Y TEXT,Longitude TEXT,Latitude TEXT
);

CREATE TABLE IF NOT EXISTS mtl_fire_fights(
 "_id" TEXT,INCIDENT_NBR TEXT,CREATION_DATE_TIME TEXT,INCIDENT_TYPE_DESC TEXT,DESCRIPTION_GROUPE TEXT,CASERNE TEXT,NOM_VILLE TEXT,NOM_ARROND TEXT,DIVISION TEXT,NOMBRE_UNITES TEXT,MTM8_X TEXT,MTM8_Y TEXT,LONGITUDE TEXT,LATITUDE TEXT
);

CREATE TABLE IF NOT EXISTS mtl_police_offices(
"_id" TEXT,NO_CIV_LIE TEXT,PREFIX_TEM TEXT,NOM_TEMP TEXT,DIR_TEMP TEXT,MUN_TEMP TEXT,DESC_LIEU TEXT,LATITUDE TEXT,LONGITUDE TEXT,X TEXT,Y TEXT
);

CREATE TABLE IF NOT EXISTS mtl_population (
"_id" TEXT,cod_geo TEXT,nom_organisme TEXT,desi_org TEXT,cod_mrc TEXT,nom_mrc TEXT,cod_cm TEXT,nom_cm TEXT,no_reg TEXT,desc_reg TEXT,type_org TEXT,population TEXT,CPAAX00015 TEXT,CPALX00015 TEXT,CPAAX00016 TEXT,CPALX00016 TEXT,CPAAX00018 TEXT,CPALX00018 TEXT,CPAAX00020 TEXT,CPALX00020 TEXT,CPAAX00021 TEXT,CPALX00021 TEXT,CPAAX00022 TEXT,CPALX00022 TEXT,CPAAX00025 TEXT,CPALX00025 TEXT,CPAAX00026 TEXT,CPALX00026 TEXT,CPAAX00027 TEXT,CPALX00027 TEXT,CPAAX00028 TEXT,CPALX00028 TEXT,CPAAX00029 TEXT,CPALX00029 TEXT,CPAAX00030 TEXT,CPALX00030 TEXT,CPAAX00032 TEXT,CPALX00032 TEXT,CPAAX00033 TEXT,CPALX00033 TEXT,CPAAX00034 TEXT,CPALX00034 TEXT,CPAAX00035 TEXT,CPALX00035 TEXT,CPAAX00037 TEXT,CPALX00037 TEXT,CPAAX00038 TEXT,CPALX00038 TEXT,CPAAX00039 TEXT,CPALX00039 TEXT,CPAAX00040 TEXT,CPALX00040 TEXT,CPAAX00041 TEXT,CPALX00041 TEXT,CPAAX00042 TEXT,CPALX00042 TEXT,CPAAX00043 TEXT,CPALX00043 TEXT,CPAAX00044 TEXT,CPALX00044 TEXT,CPAAX00045 TEXT,CPALX00045 TEXT,CPAAX00046 TEXT,CPALX00046 TEXT,CPAAX00052 TEXT,CPALX00052 TEXT,CPAAX00054 TEXT,CPALX00054 TEXT,CPAAX00055 TEXT,CPALX00055 TEXT,CPAAX00056 TEXT,CPALX00056 TEXT,CPAAX00058 TEXT,CPALX00058 TEXT,CPAAX00063 TEXT,CPALX00063 TEXT,CPAAX00064 TEXT,CPALX00064 TEXT,CPAAX00066 TEXT,CPALX00066 TEXT,CPAAX00067 TEXT,CPALX00067 TEXT,CPAAX00068 TEXT,CPALX00068 TEXT,CPAAX00069 TEXT,CPALX00069 TEXT,CPAAX00071 TEXT,CPALX00071 TEXT,CPAAX00072 TEXT,CPALX00072 TEXT,CPALX00073 TEXT,CPAAX00074 TEXT,CPALX00074 TEXT,CPALX01707 TEXT,CPALX01708 TEXT,CPALX01709 TEXT,CPALX01710 TEXT,CPALX01711 TEXT,CPALX01712 TEXT,CPALX01713 TEXT,CPALX01714 TEXT,CPALX01715 TEXT,CPALX01716 TEXT,CPALX01717 TEXT,CPALX01718 TEXT,CPAAC01723 TEXT,CPAAE01723 TEXT,CPAAF01723 TEXT,CPAAG01723 TEXT,CPAAH01723 TEXT,CPALC01723 TEXT,CPALE01723 TEXT,CPALF01723 TEXT,CPALG01723 TEXT,CPALH01723 TEXT,CPAAA01724 TEXT,CPAAB01724 TEXT,CPAAC01724 TEXT,CPAAD01724 TEXT,CPALA01724 TEXT,CPALB01724 TEXT,CPALC01724 TEXT,CPALD01724 TEXT,CPAAA01726 TEXT,CPAAB01726 TEXT,CPAAC01726 TEXT,CPAAD01726 TEXT,CPALA01726 TEXT,CPALB01726 TEXT,CPALC01726 TEXT,CPALD01726 TEXT,CPAAA01728 TEXT,CPAAB01728 TEXT,CPAAC01728 TEXT,CPAAD01728 TEXT,CPALA01728 TEXT,CPALB01728 TEXT,CPALC01728 TEXT,CPALD01728 TEXT,CPAAA01729 TEXT,CPAAB01729 TEXT,CPAAC01729 TEXT,CPAAD01729 TEXT,CPALA01729 TEXT,CPALB01729 TEXT,CPALC01729 TEXT,CPALD01729 TEXT,CPAAA01731 TEXT,CPAAB01731 TEXT,CPAAC01731 TEXT,CPAAD01731 TEXT,CPALA01731 TEXT,CPALB01731 TEXT,CPALC01731 TEXT,CPALD01731 TEXT,CPAAA01732 TEXT,CPAAB01732 TEXT,CPAAC01732 TEXT,CPAAD01732 TEXT,CPALA01732 TEXT,CPALB01732 TEXT,CPALC01732 TEXT,CPALD01732 TEXT,CPAAA01733 TEXT,CPAAB01733 TEXT,CPAAC01733 TEXT,CPAAD01733 TEXT,CPALA01733 TEXT,CPALB01733 TEXT,CPALC01733 TEXT,CPALD01733 TEXT,CPAAC01735 TEXT,CPAAE01735 TEXT,CPAAF01735 TEXT,CPAAG01735 TEXT,CPAAH01735 TEXT,CPALC01735 TEXT,CPALE01735 TEXT,CPALF01735 TEXT,CPALG01735 TEXT,CPALH01735 TEXT,CPAAA01736 TEXT,CPAAB01736 TEXT,CPAAC01736 TEXT,CPAAD01736 TEXT,CPALA01736 TEXT,CPALB01736 TEXT,CPALC01736 TEXT,CPALD01736 TEXT,CPAAA01738 TEXT,CPAAB01738 TEXT,CPAAC01738 TEXT,CPAAD01738 TEXT,CPALA01738 TEXT,CPALB01738 TEXT,CPALC01738 TEXT,CPALD01738 TEXT,CPAAA01740 TEXT,CPAAB01740 TEXT,CPAAC01740 TEXT,CPAAD01740 TEXT,CPALA01740 TEXT,CPALB01740 TEXT,CPALC01740 TEXT,CPALD01740 TEXT,CPAAA01741 TEXT,CPAAB01741 TEXT,CPAAC01741 TEXT,CPAAD01741 TEXT,CPALA01741 TEXT,CPALB01741 TEXT,CPALC01741 TEXT,CPALD01741 TEXT,CPAAA01743 TEXT,CPAAB01743 TEXT,CPAAC01743 TEXT,CPAAD01743 TEXT,CPALA01743 TEXT,CPALB01743 TEXT,CPALC01743 TEXT,CPALD01743 TEXT,CPAAA01744 TEXT,CPAAB01744 TEXT,CPAAC01744 TEXT,CPAAD01744 TEXT,CPALA01744 TEXT,CPALB01744 TEXT,CPALC01744 TEXT,CPALD01744 TEXT,CPAAA01745 TEXT,CPAAB01745 TEXT,CPAAC01745 TEXT,CPAAD01745 TEXT,CPALA01745 TEXT,CPALB01745 TEXT,CPALC01745 TEXT,CPALD01745 TEXT,CPAAC01746 TEXT,CPAAE01746 TEXT,CPAAF01746 TEXT,CPAAG01746 TEXT,CPAAH01746 TEXT,CPALC01746 TEXT,CPALE01746 TEXT,CPALF01746 TEXT,CPALG01746 TEXT,CPALH01746 TEXT,CPAAA01747 TEXT,CPAAB01747 TEXT,CPAAC01747 TEXT,CPAAD01747 TEXT,CPALA01747 TEXT,CPALB01747 TEXT,CPALC01747 TEXT,CPALD01747 TEXT,CPAAA01749 TEXT,CPAAB01749 TEXT,CPAAC01749 TEXT,CPAAD01749 TEXT,CPALA01749 TEXT,CPALB01749 TEXT,CPALC01749 TEXT,CPALD01749 TEXT,CPAAA01751 TEXT,CPAAB01751 TEXT,CPAAC01751 TEXT,CPAAD01751 TEXT,CPALA01751 TEXT,CPALB01751 TEXT,CPALC01751 TEXT,CPALD01751 TEXT,CPAAA01752 TEXT,CPAAB01752 TEXT,CPAAC01752 TEXT,CPAAD01752 TEXT,CPALA01752 TEXT,CPALB01752 TEXT,CPALC01752 TEXT,CPALD01752 TEXT,CPAAA01754 TEXT,CPAAB01754 TEXT,CPAAC01754 TEXT,CPAAD01754 TEXT,CPALA01754 TEXT,CPALB01754 TEXT,CPALC01754 TEXT,CPALD01754 TEXT,CPAAA01755 TEXT,CPAAB01755 TEXT,CPAAC01755 TEXT,CPAAD01755 TEXT,CPALA01755 TEXT,CPALB01755 TEXT,CPALC01755 TEXT,CPALD01755 TEXT,CPAAA01756 TEXT,CPAAB01756 TEXT,CPAAC01756 TEXT,CPAAD01756 TEXT,CPALA01756 TEXT,CPALB01756 TEXT,CPALC01756 TEXT,CPALD01756 TEXT,CPAAC01757 TEXT,CPAAE01757 TEXT,CPAAF01757 TEXT,CPAAG01757 TEXT,CPAAH01757 TEXT,CPALC01757 TEXT,CPALE01757 TEXT,CPALF01757 TEXT,CPALG01757 TEXT,CPALH01757 TEXT,CPAAA01758 TEXT,CPAAB01758 TEXT,CPAAC01758 TEXT,CPAAD01758 TEXT,CPALA01758 TEXT,CPALB01758 TEXT,CPALC01758 TEXT,CPALD01758 TEXT,CPAAA01760 TEXT,CPAAB01760 TEXT,CPAAC01760 TEXT,CPAAD01760 TEXT,CPALA01760 TEXT,CPALB01760 TEXT,CPALC01760 TEXT,CPALD01760 TEXT,CPAAA01762 TEXT,CPAAB01762 TEXT,CPAAC01762 TEXT,CPAAD01762 TEXT,CPALA01762 TEXT,CPALB01762 TEXT,CPALC01762 TEXT,CPALD01762 TEXT,CPAAA01763 TEXT,CPAAB01763 TEXT,CPAAC01763 TEXT,CPAAD01763 TEXT,CPALA01763 TEXT,CPALB01763 TEXT,CPALC01763 TEXT,CPALD01763 TEXT,CPAAA01765 TEXT,CPAAB01765 TEXT,CPAAC01765 TEXT,CPAAD01765 TEXT,CPALA01765 TEXT,CPALB01765 TEXT,CPALC01765 TEXT,CPALD01765 TEXT,CPAAA01766 TEXT,CPAAB01766 TEXT,CPAAC01766 TEXT,CPAAD01766 TEXT,CPALA01766 TEXT,CPALB01766 TEXT,CPALC01766 TEXT,CPALD01766 TEXT,CPAAA01767 TEXT,CPAAB01767 TEXT,CPAAC01767 TEXT,CPAAD01767 TEXT,CPALA01767 TEXT,CPALB01767 TEXT,CPALC01767 TEXT,CPALD01767 TEXT,CPAAA01768 TEXT,CPAAB01768 TEXT,CPAAC01768 TEXT,CPAAD01768 TEXT,CPAAE01768 TEXT,CPAAF01768 TEXT,CPAAG01768 TEXT,CPAAH01768 TEXT,CPALA01768 TEXT,CPALB01768 TEXT,CPALC01768 TEXT,CPALD01768 TEXT,CPALE01768 TEXT,CPALF01768 TEXT,CPALG01768 TEXT,CPALH01768 TEXT,CPAAX01771 TEXT,CPALX01771 TEXT,CPAAX01772 TEXT,CPALX01772 TEXT,CPAAX01773 TEXT,CPALX01773 TEXT,CPAAX01774 TEXT,CPALX01774 TEXT,CPAAX01775 TEXT,CPALX01775 TEXT,CPAAA01780 TEXT,CPAAB01780 TEXT,CPAAC01780 TEXT,CPAAD01780 TEXT,CPAAF01780 TEXT,CPAAG01780 TEXT,CPAAH01780 TEXT,CPAAI01780 TEXT,CPAAK01780 TEXT,CPAAX01780 TEXT,CPALA01780 TEXT,CPALB01780 TEXT,CPALC01780 TEXT,CPALD01780 TEXT,CPALF01780 TEXT,CPALG01780 TEXT,CPALH01780 TEXT,CPALI01780 TEXT,CPALK01780 TEXT,CPALX01780 TEXT,CPAAA01782 TEXT,CPAAB01782 TEXT,CPAAC01782 TEXT,CPAAD01782 TEXT,CPAAF01782 TEXT,CPAAG01782 TEXT,CPAAH01782 TEXT,CPAAI01782 TEXT,CPAAK01782 TEXT,CPAAX01782 TEXT,CPALA01782 TEXT,CPALB01782 TEXT,CPALC01782 TEXT,CPALD01782 TEXT,CPALF01782 TEXT,CPALG01782 TEXT,CPALH01782 TEXT,CPALI01782 TEXT,CPALK01782 TEXT,CPALX01782 TEXT,CPAAA01783 TEXT,CPAAB01783 TEXT,CPAAC01783 TEXT,CPAAD01783 TEXT,CPAAF01783 TEXT,CPAAG01783 TEXT,CPAAH01783 TEXT,CPAAI01783 TEXT,CPAAK01783 TEXT,CPAAX01783 TEXT,CPALA01783 TEXT,CPALB01783 TEXT,CPALC01783 TEXT,CPALD01783 TEXT,CPALF01783 TEXT,CPALG01783 TEXT,CPALH01783 TEXT,CPALI01783 TEXT,CPALK01783 TEXT,CPALX01783 TEXT,CPAAA01784 TEXT,CPAAB01784 TEXT,CPAAC01784 TEXT,CPAAD01784 TEXT,CPAAF01784 TEXT,CPAAG01784 TEXT,CPAAH01784 TEXT,CPAAI01784 TEXT,CPAAK01784 TEXT,CPAAX01784 TEXT,CPALA01784 TEXT,CPALB01784 TEXT,CPALC01784 TEXT,CPALD01784 TEXT,CPALF01784 TEXT,CPALG01784 TEXT,CPALH01784 TEXT,CPALI01784 TEXT,CPALK01784 TEXT,CPALX01784 TEXT,CPAAA01787 TEXT,CPAAB01787 TEXT,CPAAC01787 TEXT,CPAAD01787 TEXT,CPAAF01787 TEXT,CPAAG01787 TEXT,CPAAH01787 TEXT,CPAAI01787 TEXT,CPAAK01787 TEXT,CPAAX01787 TEXT,CPALA01787 TEXT,CPALB01787 TEXT,CPALC01787 TEXT,CPALD01787 TEXT,CPALF01787 TEXT,CPALG01787 TEXT,CPALH01787 TEXT,CPALI01787 TEXT,CPALK01787 TEXT,CPALX01787 TEXT,CPAAA01788 TEXT,CPAAB01788 TEXT,CPAAC01788 TEXT,CPAAD01788 TEXT,CPAAF01788 TEXT,CPAAG01788 TEXT,CPAAH01788 TEXT,CPAAI01788 TEXT,CPAAK01788 TEXT,CPAAX01788 TEXT,CPALA01788 TEXT,CPALB01788 TEXT,CPALC01788 TEXT,CPALD01788 TEXT,CPALF01788 TEXT,CPALG01788 TEXT,CPALH01788 TEXT,CPALI01788 TEXT,CPALK01788 TEXT,CPALX01788 TEXT,CPAAA01790 TEXT,CPAAB01790 TEXT,CPAAC01790 TEXT,CPAAK01790 TEXT,CPAAX01790 TEXT,CPALA01790 TEXT,CPALB01790 TEXT,CPALC01790 TEXT,CPALK01790 TEXT,CPALX01790 TEXT,CPAAA01791 TEXT,CPAAB01791 TEXT,CPAAC01791 TEXT,CPAAK01791 TEXT,CPAAX01791 TEXT,CPALA01791 TEXT,CPALB01791 TEXT,CPALC01791 TEXT,CPALK01791 TEXT,CPALX01791 TEXT,CPAAX01793 TEXT,CPALX01793 TEXT,CPAAX01794 TEXT,CPALX01794 TEXT,CPAAX01795 TEXT,CPALX01795 TEXT,CPAAX01797 TEXT,CPALX01797 TEXT,CPAAX01799 TEXT,CPALX01799 TEXT,CPAAX01800 TEXT,CPALX01800 TEXT,CPAAX01801 TEXT,CPALX01801 TEXT,CPAAX01802 TEXT,CPALX01802 TEXT,CPAAX01803 TEXT,CPALX01803 TEXT,CPAAX01804 TEXT,CPALX01804 TEXT,CPALX01805 TEXT,CPALX01806 TEXT,CPAIX01807 TEXT,CPAIX01808 TEXT,CPAIX01809 TEXT,CPAIX01810 TEXT,CPAAX01242 TEXT,CPAAX01569 TEXT,CPALX01642 TEXT,CPALX01778 TEXT,CPAAX01898 TEXT,CPALX01898 TEXT,CPAAX01899 TEXT,CPALX01899 TEXT,CPAAA01904 TEXT,CPAAB01904 TEXT,CPAAC01904 TEXT,CPAAD01904 TEXT,CPALA01904 TEXT,CPALB01904 TEXT,CPALC01904 TEXT,CPALD01904 TEXT,CPAAA01905 TEXT,CPAAB01905 TEXT,CPAAC01905 TEXT,CPAAD01905 TEXT,CPALA01905 TEXT,CPALB01905 TEXT,CPALC01905 TEXT,CPALD01905 TEXT,CPAAA01906 TEXT,CPAAB01906 TEXT,CPAAC01906 TEXT,CPAAD01906 TEXT,CPALA01906 TEXT,CPALB01906 TEXT,CPALC01906 TEXT,CPALD01906 TEXT,CPAAA01907 TEXT,CPAAB01907 TEXT,CPAAC01907 TEXT,CPAAD01907 TEXT,CPALA01907 TEXT,CPALB01907 TEXT,CPALC01907 TEXT,CPALD01907 TEXT,CPAAX01924 TEXT,CPALX01924 TEXT,CPAAX01925 TEXT,CPALX01925 TEXT,CPAAX01938 TEXT,CPALX01938 TEXT,CPAAX02029 TEXT,CPALX02029 TEXT,CPALX02105 TEXT,CPALX02106 TEXT,CPAAX02137 TEXT,CPALX02137 TEXT,CPAAX02138 TEXT,CPALX02138 TEXT,CPAAX02263 TEXT,CPALX02263 TEXT,CPALX02265 TEXT,CPAAX02267 TEXT,CPALX02267 TEXT,CPAAX02268 TEXT,CPALX02268 TEXT,CPAAX02269 TEXT,CPALX02269 TEXT,CPALX02274 TEXT,CPALX02276 TEXT,CPALX02277 TEXT,CPALX02278 TEXT,CPALX02280 TEXT,CPALX02282 TEXT,CPALX02283 TEXT,CPALX02284 TEXT,CPAAA02285 TEXT,CPAAB02285 TEXT,CPAAC02285 TEXT,CPAAD02285 TEXT,CPALA02285 TEXT,CPALB02285 TEXT,CPALC02285 TEXT,CPALD02285 TEXT,CPAAA02286 TEXT,CPAAB02286 TEXT,CPAAC02286 TEXT,CPAAD02286 TEXT,CPALA02286 TEXT,CPALB02286 TEXT,CPALC02286 TEXT,CPALD02286 TEXT,CPAAA02287 TEXT,CPAAB02287 TEXT,CPAAC02287 TEXT,CPAAD02287 TEXT,CPALA02287 TEXT,CPALB02287 TEXT,CPALC02287 TEXT,CPALD02287 TEXT,CPAAA02288 TEXT,CPAAB02288 TEXT,CPAAC02288 TEXT,CPAAD02288 TEXT,CPALA02288 TEXT,CPALB02288 TEXT,CPALC02288 TEXT,CPALD02288 TEXT
);

CREATE TABLE IF NOT EXISTS mtl_public_sites (
"_id" TEXT,titre_lieu TEXT,url_fiche TEXT,description TEXT,date_cree TEXT,date_revision TEXT,arrondissements TEXT,"types" TEXT,installations TEXT,activites TEXT,commodites TEXT,accessibilite TEXT,categories TEXT,statut_ouverture TEXT,horaire_par_jour TEXT,commentaires_horaire TEXT,reglementation TEXT,paiement TEXT,telephone TEXT,courriel TEXT,titre_lieu_adresse_postale TEXT,adresse_principale TEXT,adresse_secondaire TEXT,code_postal TEXT,ville TEXT,lat TEXT,long TEXT,X TEXT,Y TEXT
);

CREATE TABLE IF NOT EXISTS mtl_Residential_fines (
"_id" TEXT,lieu_infraction_no_civique TEXT,lieu_infraction_rue TEXT,code_arrondissement TEXT,nom_contrevenant TEXT,article TEXT,nature_infraction TEXT,date_infraction TEXT,date_jugement TEXT,amende_imposee TEXT
);

CREATE TABLE IF NOT EXISTS quebec_data."mtl_Residential_properties" (
"_id" TEXT,ID_UEV TEXT,CIVIQUE_DEBUT TEXT,CIVIQUE_FIN TEXT,NOM_RUE TEXT,SUITE_DEBUT TEXT,MUNICIPALITE TEXT,ETAGE_HORS_SOL TEXT,NOMBRE_LOGEMENT TEXT,ANNEE_CONSTRUCTION TEXT,CODE_UTILISATION TEXT,LETTRE_DEBUT TEXT,LETTRE_FIN TEXT,LIBELLE_UTILISATION TEXT,CATEGORIE_UEF TEXT,MATRICULE83 TEXT,SUPERFICIE_TERRAIN TEXT,SUPERFICIE_BATIMENT TEXT,NO_ARROND_ILE_CUM TEXT
);

CREATE TABLE IF NOT EXISTS mtl_Rich_distribution (
"_id" TEXT,Annee_imposition TEXT,Region_administrative TEXT,Nombre_de_particuliers TEXT
);

CREATE TABLE IF NOT EXISTS mtl_retailer_construction_permit (
"_id" TEXT,no_demande TEXT,id_permis TEXT,date_debut TEXT,date_emission TEXT,emplacement TEXT,arrondissement TEXT,code_type_base_demande TEXT,description_type_demande TEXT,description_type_batiment TEXT,description_categorie_batiment TEXT,nature_travaux TEXT,nb_logements TEXT,longitude TEXT,latitude TEXT,loc_x TEXT,loc_y TEXT
);


CREATE TABLE IF NOT EXISTS mtl_bus (
"_id" TEXT,ID_GTFS TEXT,NOM TEXT,NUM_ARRET TEXT,HORAIRE_SE TEXT,HORAIRE_FDS TEXT,CIRCUIT TEXT,TYPE_POINTEUR TEXT,LATITUDE TEXT,LONGITUDE TEXT,GEOM TEXT
);


CREATE TABLE IF NOT EXISTS mtl_ardm (
"_id" TEXT,"Nom officiel" TEXT,"Nom abrege" TEXT,Acronyme TEXT,"Code 3L" TEXT,"ID-uadm" TEXT,"No-arro-election" TEXT,"Code REM" TEXT
);

CREATE TABLE IF NOT EXISTS mtl_uadm (
"_id" TEXT,"No UADM" TEXT,Description TEXT,"Type" TEXT,Service_arrondissement TEXT
);

CREATE TABLE IF NOT EXISTS to_apt_registrations (
"_id" TEXT,AIR_CONDITIONING_TYPE TEXT,AMENITIES_AVAILABLE TEXT,ANNUAL_FIRE_ALARM_TEST_RECORDS TEXT,ANNUAL_FIRE_PUMP_FLOW_TEST_RECORDS TEXT,APPROVED_FIRE_SAFETY_PLAN TEXT,BALCONIES TEXT,BARRIER_FREE_ACCESSIBILTY_ENTR TEXT,BIKE_PARKING TEXT,CONFIRMED_STOREYS TEXT,CONFIRMED_UNITS TEXT,DATE_OF_LAST_INSPECTION_BY_TSSA TEXT,DESCRIPTION_OF_CHILD_PLAY_AREA TEXT,DESCRIPTION_OF_INDOOR_EXERCISE_ROOM TEXT,DESCRIPTION_OF_OUTDOOR_REC_FACILITIES TEXT,ELEVATOR_PARTS_REPLACED TEXT,ELEVATOR_STATUS TEXT,EMERG_POWER_SUPPLY_TEST_RECORDS TEXT,EXTERIOR_FIRE_ESCAPE TEXT,FACILITIES_AVAILABLE TEXT,FIRE_ALARM TEXT,GARBAGE_CHUTES TEXT,GREEN_BIN_LOCATION TEXT,HEATING_EQUIPMENT_STATUS TEXT,HEATING_EQUIPMENT_YEAR_INSTALLED TEXT,HEATING_TYPE TEXT,INDOOR_GARBAGE_STORAGE_AREA TEXT,INTERCOM TEXT,IS_THERE_A_COOLING_ROOM TEXT,IS_THERE_EMERGENCY_POWER TEXT,LAUNDRY_ROOM TEXT,LAUNDRY_ROOM_HOURS_OF_OPERATION TEXT,LAUNDRY_ROOM_LOCATION TEXT,LOCKER_OR_STORAGE_ROOM TEXT,NO_BARRIER_FREE_ACCESSBLE_UNITS TEXT,NO_OF_ACCESSIBLE_PARKING_SPACES TEXT,NO_OF_ELEVATORS TEXT,NO_OF_LAUNDRY_ROOM_MACHINES TEXT,NON_SMOKING_BUILDING TEXT,OUTDOOR_GARBAGE_STORAGE_AREA TEXT,PARKING_TYPE TEXT,PCODE TEXT,PET_RESTRICTIONS TEXT,PETS_ALLOWED TEXT,PROP_MANAGEMENT_COMPANY_NAME TEXT,PROPERTY_TYPE TEXT,RECYCLING_BINS_LOCATION TEXT,RSN TEXT,SEPARATE_GAS_METERS_EACH_UNIT TEXT,SEPARATE_HYDRO_METER_EACH_UNIT TEXT,SEPARATE_WATER_METERS_EA_UNIT TEXT,SITE_ADDRESS TEXT,SPRINKLER_SYSTEM TEXT,SPRINKLER_SYSTEM_TEST_RECORD TEXT,SPRINKLER_SYSTEM_YEAR_INSTALLED TEXT,TSSA_TEST_RECORDS TEXT,VISITOR_PARKING TEXT,WARD TEXT,WINDOW_TYPE TEXT,YEAR_BUILT TEXT,YEAR_OF_REPLACEMENT TEXT,YEAR_REGISTERED TEXT,NO_OF_STOREYS TEXT,"IS_THERE_EMERGENCY_POWER?" TEXT,"NON-SMOKING_BUILDING" TEXT,NO_OF_UNITS TEXT,NO_OF_ACCESSIBLEPARKING_SPACES TEXT,"FACILITIES_AVAILABLE?" TEXT,"IS_THERE_A_COOLING_ROOM?" TEXT,NO_BARRIERFREE_ACCESSBLE_UNITS TEXT
);

CREATE TABLE IF NOT EXISTS to_barbers_inspections (
"_id" TEXT,estId TEXT,estName TEXT,addrFull TEXT,srvType TEXT,insStatus TEXT,insDate TEXT,observation TEXT,infCategory TEXT,defDesc TEXT,infType TEXT,actionDesc TEXT,OutcomeDate TEXT,OutcomeDesc TEXT,fineAmount TEXT,geometry TEXT
);


CREATE TABLE IF NOT EXISTS to_Bids_Solicitations (
"_id" TEXT,unique_id TEXT,"Document Number" TEXT,"RFx (Solicitation) Type" TEXT,"NOIP (Notice of Intended Procurement) Type" TEXT,"Issue Date" TEXT,"Submission Deadline" TEXT,"High Level Category" TEXT,"Solicitation Document Description" TEXT,Division TEXT,"Buyer Name" TEXT,"Buyer Email" TEXT,"Buyer Phone Number" TEXT
);

CREATE TABLE IF NOT EXISTS to_building_active_permits (
"_id" TEXT,PERMIT_NUM TEXT,REVISION_NUM TEXT,PERMIT_TYPE TEXT,STRUCTURE_TYPE TEXT,"WORK" TEXT,STREET_NUM TEXT,STREET_NAME TEXT,STREET_TYPE TEXT,STREET_DIRECTION TEXT,POSTAL TEXT,GEO_ID TEXT,WARD_GRID TEXT,APPLICATION_DATE TEXT,ISSUED_DATE TEXT,COMPLETED_DATE TEXT,STATUS TEXT,DESCRIPTION TEXT,CURRENT_USE TEXT,PROPOSED_USE TEXT,DWELLING_UNITS_CREATED TEXT,DWELLING_UNITS_LOST TEXT,EST_CONST_COST TEXT,ASSEMBLY TEXT,INSTITUTIONAL TEXT,RESIDENTIAL TEXT,BUSINESS_AND_PERSONAL_SERVICES TEXT,MERCANTILE TEXT,INDUSTRIAL TEXT,INTERIOR_ALTERATIONS TEXT,DEMOLITION TEXT,BUILDER_NAME TEXT
);

CREATE TABLE IF NOT EXISTS to_Building_permits_signs (
"_id" TEXT,PERMIT_NUMBER TEXT,"TYPE" TEXT,STREET_NUMBER TEXT,STREET_NAME TEXT,STREET_TYPE TEXT,STREET_DIRECTION TEXT,POSTAL TEXT,APPLICATION_DATE TEXT,ISSUED_DATE TEXT,COMPLETED_DATE TEXT,STATUS TEXT,CURRENT_USE TEXT,PROPOSED_USE TEXT,TOTAL_NUMBER_FACES TEXT
);

CREATE TABLE IF NOT EXISTS to_Business_permits (
"_id" TEXT,Category TEXT,"Licence No." TEXT,"Operating Name" TEXT,Issued TEXT,"Client Name" TEXT,"Business Phone" TEXT,"Business Phone Ext." TEXT,"Licence Address Line 1" TEXT,"Licence Address Line 2" TEXT,"Licence Address Line 3" TEXT,Ward TEXT,Conditions TEXT,"Free Form Conditions Line 1" TEXT,"Free Form Conditions Line 2" TEXT,"Plate No." TEXT,Endorsements TEXT,"Cancel Date" TEXT,"Last Record Update" TEXT
);

CREATE TABLE IF NOT EXISTS to_Business (
"_id" TEXT,AREA_ID TEXT,DATE_EFFECTIVE TEXT,AREA_ATTR_ID TEXT,PARENT_AREA_ID TEXT,AREA_SHORT_CODE TEXT,AREA_LONG_CODE TEXT,AREA_NAME TEXT,AREA_DESC TEXT,OBJECTID TEXT,geometry TEXT
);

CREATE TABLE IF NOT EXISTS to_crimes (
_id TEXT,AREA_NAME TEXT,HOOD_ID TEXT,POPULATION_2024 TEXT,"geometry" TEXT,crime TEXT,year TEXT,count TEXT,rate TEXT
);

CREATE TABLE IF NOT EXISTS to_cycle_parking (
"_id" TEXT,ADDRESS_POINT_ID TEXT,ADDRESS_NUMBER TEXT,LINEAR_NAME_FULL TEXT,ADDRESS_FULL TEXT,POSTAL_CODE TEXT,MUNICIPALITY TEXT,CITY TEXT,WARD_NAME TEXT,PLACE_NAME TEXT,GENERAL_USE_CODE TEXT,CENTRELINE_ID TEXT,LO_NUM TEXT,LO_NUM_SUF TEXT,HI_NUM TEXT,HI_NUM_SUF TEXT,LINEAR_NAME_ID TEXT,MI_PRINX TEXT,OBJECTID TEXT,"ID" TEXT,STATION_TYPE TEXT,TRANSIT_STATION TEXT,FLANKING TEXT,BIKE_CAPACITY TEXT,CHANGE_ROOM TEXT,VENDING_MACHINE TEXT,TOOLS_PUMP TEXT,YR_INSTALL TEXT,geometry TEXT
);

CREATE TABLE IF NOT EXISTS to_fines_buidlings (
"_id" TEXT,RSN TEXT,YEAR_REGISTERED TEXT,YEAR_EVALUATED TEXT,YEAR_BUILT TEXT,PROPERTY_TYPE TEXT,WARD TEXT,WARDNAME TEXT,SITE_ADDRESS TEXT,CONFIRMED_STOREYS TEXT,CONFIRMED_UNITS TEXT,EVALUATION_COMPLETED_ON TEXT,SCORE TEXT,RESULTS_OF_SCORE TEXT,NO_OF_AREAS_EVALUATED TEXT,ENTRANCE_LOBBY TEXT,ENTRANCE_DOORS_WINDOWS TEXT,"SECURITY" TEXT,STAIRWELLS TEXT,LAUNDRY_ROOMS TEXT,INTERNAL_GUARDS_HANDRAILS TEXT,GARBAGE_CHUTE_ROOMS TEXT,GARBAGE_BIN_STORAGE_AREA TEXT,ELEVATORS TEXT,STORAGE_AREAS_LOCKERS TEXT,INTERIOR_WALL_CEILING_FLOOR TEXT,INTERIOR_LIGHTING_LEVELS TEXT,GRAFFITI TEXT,EXTERIOR_CLADDING TEXT,EXTERIOR_GROUNDS TEXT,EXTERIOR_WALKWAYS TEXT,BALCONY_GUARDS TEXT,WATER_PEN_EXT_BLDG_ELEMENTS TEXT,PARKING_AREA TEXT,OTHER_FACILITIES TEXT,GRID TEXT,LATITUDE TEXT,LONGITUDE TEXT,X TEXT,Y TEXT,"YEAR REGISTERED" TEXT,"YEAR BUILT" TEXT,"YEAR EVALUATED" TEXT,"PROPERTY TYPE" TEXT,"SITE ADDRESS" TEXT,"CONFIRMED STOREYS" TEXT,"CONFIRMED UNITS" TEXT,"EVALUATION COMPLETED ON" TEXT,"CURRENT BUILDING EVAL SCORE" TEXT,"PROACTIVE BUILDING SCORE" TEXT,"CURRENT REACTIVE SCORE" TEXT,"NO OF AREAS EVALUATED" TEXT,"NUMBERING OF PROPERTY" TEXT,"EXTERIOR GROUNDS" TEXT,FENCING TEXT,"RETAINING WALLS" TEXT,"CATCH BASINS / STORM DRAINAGE" TEXT,"BUILDING EXTERIOR" TEXT,"BALCONY GUARDS" TEXT,WINDOWS TEXT,"EXT. RECEPTACLE STORAGE AREA" TEXT,"EXTERIOR WALKWAYS" TEXT,"CLOTHING DROP BOXES" TEXT,"ACCESSORY BUILDINGS" TEXT,INTERCOM TEXT,"EMERGENCY CONTACT SIGN" TEXT,"LOBBY - WALLS AND CEILING" TEXT,"LOBBY FLOORS" TEXT,"LAUNDRY ROOM" TEXT,"INT. RECEPTACLE STORAGE AREA" TEXT,"MAIL RECEPTACLES" TEXT,"EXTERIOR DOORS" TEXT,"STORAGE AREAS/LOCKERS MAINT." TEXT,POOLS TEXT,"OTHER AMENITIES" TEXT,"PARKING AREAS" TEXT,"ABANDONED EQUIP./DERELICT VEH." TEXT,"GARBAGE/COMPACTOR ROOM" TEXT,"ELEVATOR MAINTENANCE" TEXT,"ELEVATOR COSMETICS" TEXT,"INT. HALLWAY - WALLS / CEILING" TEXT,"INTERIOR HALLWAY FLOORS" TEXT,"INT. LOBBY / HALLWAY LIGHTING" TEXT,"COMMON AREA VENTILATION" TEXT,"ELECTRICAL SERVICES / OUTLETS" TEXT,"CHUTE ROOMS - MAINTENANCE" TEXT,"STAIRWELL - WALLS AND CEILING" TEXT,"STAIRWELL - LANDING AND STEPS" TEXT,"STAIRWELL LIGHTING" TEXT,"INT. HANDRAIL / GUARD - SAFETY" TEXT,"INT. HANDRAIL / GUARD - MAINT." TEXT,"BUILDING CLEANLINESS" TEXT,"COMMON AREA PESTS" TEXT,"TENANT NOTIFICATION BOARD" TEXT,"PEST CONTROL LOG" TEXT,"MAINTENANCE LOG" TEXT,"CLEANING LOG" TEXT,"VITAL SERVICE PLAN" TEXT,"ELECTRICAL SAFETY PLAN" TEXT,"STATE OF GOOD REPAIR PLAN" TEXT,"TENANT SERVICE REQUEST LOG" TEXT
);

CREATE TABLE IF NOT EXISTS to_fines_food (
"_id" TEXT,"Establishment ID" TEXT,"Inspection ID" TEXT,"Establishment Name" TEXT,"Establishment Type" TEXT,"Establishment Address" TEXT,"Establishment Status" TEXT,"Min. Inspections Per Year" TEXT,"Infraction Details" TEXT,"Inspection Date" TEXT,Severity TEXT,"Action" TEXT,Outcome TEXT,"Amount Fined" TEXT,Latitude TEXT,Longitude TEXT,unique_id TEXT
);

CREATE TABLE IF NOT EXISTS to_fire_fights (
"_id" TEXT,Incident_Number TEXT,Initial_CAD_Event_Type TEXT,Final_Incident_Type TEXT,Exposures TEXT,Incident_Station_Area TEXT,Incident_Ward TEXT,"Intersection" TEXT,Latitude TEXT,Longitude TEXT,Property_Use TEXT,Building_Status TEXT,TFS_Alarm_Time TEXT,TFS_Arrival_Time TEXT,Ext_agent_app_or_defer_time TEXT,Fire_Under_Control_Time TEXT,Last_TFS_Unit_Clear_Time TEXT,Number_of_responding_apparatus TEXT,Number_of_responding_personnel TEXT,Count_of_Persons_Rescued TEXT,TFS_Firefighter_Casualties TEXT,Civilian_Casualties TEXT,Estimated_Number_Of_Persons_Displaced TEXT,Estimated_Dollar_Loss TEXT,Business_Impact TEXT,Status_of_Fire_On_Arrival TEXT,Method_Of_Fire_Control TEXT,Area_of_Origin TEXT,Level_Of_Origin TEXT,Extent_Of_Fire TEXT,Smoke_Spread TEXT,Ignition_Source TEXT,Material_First_Ignited TEXT,Possible_Cause TEXT,Smoke_Alarm_at_Fire_Origin TEXT,Smoke_Alarm_at_Fire_Origin_Alarm_Failure TEXT,Smoke_Alarm_at_Fire_Origin_Alarm_Type TEXT,Smoke_Alarm_Impact_on_Persons_Evacuating_Impact_on_Evacuation TEXT,Fire_Alarm_System_Presence TEXT,Fire_Alarm_System_Operation TEXT,Fire_Alarm_System_Impact_on_Evacuation TEXT,Sprinkler_System_Presence TEXT,Sprinkler_System_Operation TEXT
);

CREATE TABLE IF NOT EXISTS to_fire_inspections (
"_id" TEXT,PropertyAddress TEXT,ADDRESS_NUMBER TEXT,ADDRESS_NAME TEXT,Enforcement_Proceedings TEXT,PropertyType TEXT,propertyWard TEXT,InspectionThread TEXT,INSPECTIONS_OPENDATE TEXT,INSPECTIONS_CLOSEDDATE TEXT,VIOLATION_FIRE_CODE TEXT,VIOLATIONS_ITEM_NUMBER TEXT,VIOLATION_DESCRIPTION TEXT
);


CREATE TABLE IF NOT EXISTS to_food_establishments (
"_id" TEXT,INTERVENTION_TYPE TEXT,LICENCE_NUMBER TEXT,OPERATOR_NAME TEXT,BUSINESS_ADDRESS TEXT,PROPOSED_STREET_LOCATION TEXT,WARD_NAME TEXT,BIA_NAME TEXT,STREET_NAME_SHORTENED TEXT,MUNICIPAL_ADDRESS TEXT,CATEGORY TEXT,CONDITIONS TEXT,geometry TEXT
);

CREATE TABLE IF NOT EXISTS to_green_energy_installations (
"_id" TEXT,ADDRESS_POINT_ID TEXT,ADDRESS_POINT_ID_LINK TEXT,ADDRESS_NUMBER TEXT,LINEAR_NAME_FULL TEXT,ADDRESS_FULL TEXT,POSTAL_CODE TEXT,MUNICIPALITY TEXT,CITY TEXT,WARD TEXT,PLACE_NAME TEXT,GENERAL_USE_CODE TEXT,GENERAL_USE TEXT,CENTRELINE_ID TEXT,CENTRELINE_SIDE TEXT,CENTRELINE_MEASURE TEXT,ADDRESS_CLASS_DESC TEXT,LO_NUM TEXT,LO_NUM_SUF TEXT,HI_NUM TEXT,HI_NUM_SUF TEXT,LINEAR_NAME_ID TEXT,X TEXT,Y TEXT,LONGITUDE TEXT,LATITUDE TEXT,ID TEXT,BUILDING_NAME TEXT,CLIENT_ADDRESS TEXT,TYPE_INSTALL TEXT,YEAR_INSTALL TEXT,SIZE_INSTALL TEXT,UNIT_MAX_POWER TEXT,ENERGY_OUTPUT TEXT,UNIT_ANNUAL TEXT,LANDLORD TEXT,SYSTEM_OWNERSHIP TEXT,FORMER_MUNICIPALITY TEXT,CLIENT_ADDR_POINT_ID TEXT,OBJECTID TEXT,geometry TEXT
);


CREATE TABLE IF NOT EXISTS to_green_roofs (
"_id" TEXT,APPLICATION_DATE TEXT,COMPLETED_DATE TEXT,DESCRIPTION TEXT,GREEN_ROOF_AREA TEXT,GREEN_ROOF_VARIATION_AREA TEXT,ISSUED_DATE TEXT,PERMIT_NUM TEXT,PERMIT_TYPE TEXT,POSTAL TEXT,REVISION_NUM TEXT,STATUS TEXT,STREET_DIRECTION TEXT,STREET_NAME TEXT,STREET_NUM TEXT,STREET_TYPE TEXT,STRUCTURE_TYPE TEXT
);


CREATE TABLE IF NOT EXISTS to_health_outbreaks (
"_id" TEXT,"Institution Name" TEXT,"Institution Address" TEXT,"Outbreak Setting" TEXT,"Type of Outbreak" TEXT,"Causative Agent-1" TEXT,"Causative Agent-2" TEXT,"Date Outbreak Began" TEXT,"Date Declared Over" TEXT,Active TEXT,"Causative Agent - 1" TEXT,"Causative Agent - 2" TEXT
);


CREATE TABLE IF NOT EXISTS to_KPIS (
"_id" TEXT,measure_id TEXT,measure_name TEXT,interval_type TEXT,value_type TEXT,measure_value TEXT,year_to_date_variance TEXT,budget_variance TEXT,decimal_accuracy TEXT,desired_direction TEXT,category TEXT,data_source_notes TEXT,city_perspective_note TEXT,"year" TEXT,period_number_in_year TEXT,target TEXT,note TEXT
);

CREATE TABLE IF NOT EXISTS to_neighbourhood (
"_id" TEXT,Category TEXT,Topic TEXT,Characteristic TEXT,"Attribute" TEXT,Neighborhood TEXT,record TEXT
);

CREATE TABLE IF NOT EXISTS to_housing_density (
"_id" TEXT,"Licence Number" TEXT,"Permit Type" TEXT,"Operating Name" TEXT,"Client Name" TEXT,Address TEXT,"Location Name" TEXT,Ward TEXT,"Issue Date" TEXT,"Expected End Date" TEXT,"Actual End Date" TEXT,"Public Conditions" TEXT,"Hours of Operation" TEXT
);

CREATE TABLE IF NOT EXISTS to_noisy_places (
"_id" TEXT,"Licence Number" TEXT,"Permit Type" TEXT,"Operating Name" TEXT,"Client Name" TEXT,Address TEXT,"Location Name" TEXT,Ward TEXT,"Issue Date" TEXT,"Expected End Date" TEXT,"Actual End Date" TEXT,"Public Conditions" TEXT,"Hours of Operation" TEXT
);


CREATE TABLE IF NOT EXISTS to_non_competitive_contracts (
"_id" TEXT,unique_id TEXT,"Workspace Number" TEXT,Reason TEXT,"Contract Date" TEXT,"Supplier Name" TEXT,"Contract Amount" TEXT,Division TEXT,"Supplier Address" TEXT
);


CREATE TABLE IF NOT EXISTS to_on_street_permit_parking_area_maps (
"_id" TEXT,AREA_ID TEXT,DATE_EFFECTIVE TEXT,DATE_EXPIRY TEXT,AREA_ATTR_ID TEXT,AREA_TYPE_ID TEXT,PARENT_AREA_ID TEXT,AREA_TYPE TEXT,AREA_CLASS_ID TEXT,AREA_CLASS TEXT,AREA_SHORT_CODE TEXT,AREA_LONG_CODE TEXT,AREA_NAME TEXT,AREA_DESC TEXT,FEATURE_CODE TEXT,FEATURE_CODE_DESC TEXT,TRANS_ID_CREATE TEXT,TRANS_ID_EXPIRE TEXT,OBJECTID TEXT,geometry TEXT
);


CREATE TABLE IF NOT EXISTS to_real_estate_inventory (
"_id" TEXT,OBJECTID TEXT,FLOC_ID TEXT,"Building Description" TEXT,Address TEXT,City TEXT,"Ward Name" TEXT,"Former Municipality" TEXT,District TEXT,"City Cluster" TEXT,"Building Type" TEXT,"Building Status" TEXT,Jurisdiction TEXT,Management TEXT,"Owner" TEXT,"Gross Floor Area (M2)" TEXT,"Gross Floor Area (FT2)" TEXT,"Year Built" TEXT,WARD TEXT,geometry TEXT,"Property Description" TEXT,"Intersection" TEXT,"Ward \#" TEXT,"Property Type" TEXT,"Property Status" TEXT,"Area (M2)" TEXT,"Frontage (M)" TEXT,"Depth (M)" TEXT,"Area (FT2)" TEXT,"Frontage (FT)" TEXT,"Depth (FT)" TEXT
);



CREATE TABLE IF NOT EXISTS to_short_rentals (
"_id" TEXT,operator_registration_number TEXT,address TEXT,unit TEXT,postal_code TEXT,property_type TEXT,ward_number TEXT,ward_name TEXT
);

CREATE TABLE IF NOT EXISTS to_sites_opportunities (
"_id" TEXT,objectid TEXT,"id" TEXT,site_name TEXT,district TEXT,"statement" TEXT,closest_major_intersection TEXT,status TEXT,property_type_primary TEXT,property_type_secondary TEXT,"comments" TEXT,total_site_area_acres TEXT,site_area_range_1 TEXT,site_area_range2 TEXT,sq_ft_available TEXT,sq_ft_available_range1 TEXT,sq_ft_available_range2 TEXT,frontage_feet TEXT,asking_price TEXT,planning_status TEXT,planning_status_zoning TEXT,planning_status_zoning_url TEXT,planning_status_city_ward TEXT,owner TEXT,owners_rep1_name TEXT,title1 TEXT,company1 TEXT,phone1 TEXT,email1 TEXT,url_1a TEXT,url_1b TEXT,owners_rep2_name TEXT,title2 TEXT,company2 TEXT,phone2 TEXT,email2 TEXT,url_2a TEXT,url_2b TEXT,city_of_toronto_economic_develo TEXT,phone3 TEXT,email3 TEXT,photo1_path TEXT,photo2_path TEXT,photo3_path TEXT,photo1_alt_text TEXT,photo2_alt_text TEXT,photo3_alt_text TEXT,geometry TEXT
);

CREATE TABLE IF NOT EXISTS to_transportation_cycle (
"_id" TEXT,ADDRESS_POINT_ID TEXT,ADDRESS_NUMBER TEXT,LINEAR_NAME_FULL TEXT,ADDRESS_FULL TEXT,POSTAL_CODE TEXT,MUNICIPALITY TEXT,CITY TEXT,CENTRELINE_ID TEXT,LO_NUM TEXT,LO_NUM_SUF TEXT,HI_NUM TEXT,HI_NUM_SUF TEXT,LINEAR_NAME_ID TEXT,WARD_NAME TEXT,MI_PRINX TEXT,OBJECTID TEXT,CAPACITY TEXT,MULTIMODAL TEXT,SEASONAL TEXT,SHELTERED TEXT,SURFACE TEXT,STATUS TEXT,"LOCATION" TEXT,NOTES TEXT,MAP_CLASS TEXT,geometry TEXT
);

CREATE TABLE IF NOT EXISTS to_wards (
"_id" TEXT,AREA_ID TEXT,DATE_EFFECTIVE TEXT,DATE_EXPIRY TEXT,AREA_ATTR_ID TEXT,AREA_TYPE_ID TEXT,PARENT_AREA_ID TEXT,AREA_TYPE TEXT,AREA_CLASS_ID TEXT,AREA_CLASS TEXT,AREA_SHORT_CODE TEXT,AREA_LONG_CODE TEXT,AREA_NAME TEXT,AREA_DESC TEXT,FEATURE_CODE TEXT,FEATURE_CODE_DESC TEXT,TRANS_ID_CREATE TEXT,TRANS_ID_EXPIRE TEXT,OBJECTID TEXT,geometry TEXT
);
